apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.appName }}-svc
  labels:
    app: {{ .Values.labels.appName }}
spec:
  type: {{ .Values.service.type }}
  selector: 
    app: {{ .Values.labels.appName }}
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: 8080
    targetPort: 80
